# Example configuration for Black.

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''





# see https://github.com/SamGuay/Dcm2Bids/blob/master/pyproject.toml
# [tool.portray]
# host = "0.0.0.0"
# modules = ["clu.phontools"]
# docs_dir = "docs"
# include_reference_documentation = true

# [[tool.portray.extra_markdown_extensions]]
# [tool.portray.extra_markdown_extensions.toc]
# permalink = true

# [[tool.portray.extra_markdown_extensions]]
# [tool.portray.extra_markdown_extensions."pymdownx.highlight"]
# #linenums = true

# [tool.portray.mkdocs]
# # Repository
# site_name = "clu-phontools"
# repo_name = "clu-ling/clu-phontools" # Name in top right corner
# # Set repo_url so anyone running from their own repo can see from true repo.
# repo_url = "https://github.com/clu-ling/clu-phontools"
# edit_uri = "blob/master/" # Bring to the page on GH, but it won't open the _edit_ mode.
# documentation_url = "https://clu-ling/github.io/clu-phontools"

# # Left navigation menu
# nav = [
#   {  Home = "docs/intro.md" },
#   { Installation = "docs/install.md" },
#   { Usage  = "docs/tutorial.md" },
#   { Develop = "docs/develop.md" },
#   { Contributing = "docs/contributing.md" }
# ]

# extra_css = ["docs/stylesheets/extra.css"] # To fix some colors in light vs slate mode.

# # Add a bunch of markdown extensions to improve the documentation (and the look ;)).
# # See https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
# # for full list of extensions.
# markdown_extensions = ["admonition",
#                        "footnotes",
#                        "pymdownx.emoji",
#                        "pymdownx.caret",
#                        "pymdownx.mark",
#                        "pymdownx.tilde",
#                        "pymdownx.details",
#                        "pymdownx.superfences",
#                        "pymdownx.tabbed"]

# # TODO: Implement plugin so git info is displayed on each page,
# # issue has been open on portray to fix the bug.
# # plugins = ["git-revision-date", "git-revision-date-localized", "bibtext"]

# [tool.portray.mkdocs.theme]
# name = "material" # "rtd-dropdown" "readthedocs"
# # Blurb that is output when the doc site is shared on social media or elsewhere.
# site_description = """
#   This is the documentation for clu-phontools, a suite of utilities related to phonological analysis.
#   """

# # Design related stuff

# icon = {repo = "fontawesome/brands/github"} # icon in top-right corner.
# # TODO: Design a logo and/or favicon.
# # favicon = "art/logo_small.png"
# # logo = "art/logo_small.png"

# palette = {scheme = "preference"}
# # Alternative way of setting multiple option for the palette
# # [[tool.portray.mkdocs.theme.palette]]
# # scheme = "preference"

# ## Footer icon in bottom-right corner
# [[tool.portray.mkdocs.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/clu-ling/clu-phontools"
# name = "clu-phontools on GitHub"

# [[tool.portray.mkdocs.plugins]]
# [tool.portray.mkdocs.plugins.search]
# # https://github.com/daizutabi/mkapi/
# [tool.portray.mkdocs.plugins.mkapi]
# see https://github.com/mercari/mkdocs-git-snippet
#[tool.portray.mkdocs.plugins.git-snippet]
# see https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
#[tool.portray.mkdocs.plugins.git-revision-date-localized]
# see https://github.com/timvink/mkdocs-git-authors-plugin
#[tool.portray.mkdocs.plugins.git-authors]
