name: Project CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.sha.outputs.sha_short }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate short commit hash
      id: sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  python:
    name: "Python library"
    runs-on: ubuntu-latest
    needs: setup
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
    # Setup docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Library (docker)
    - name: "Build docker image (experiments)"
      #working-directory: ./
      run: docker build -f Dockerfile -t "parsertongue/realine:latest" -t "parsertongue/realine:${{ needs.setup.outputs.sha_short }}" .
    # Tests
    - name: "Tests and coverage (experiments)"
      run: |
        docker run -i "parsertongue/realine:latest" green -vvv /app
    # Type checks
    - name: "Type checks (experiments)"
      continue-on-error: true
      run : |
        docker run -i "parsertongue/realine:latest" mypy --ignore-missing-imports --follow-imports=skip --strict-optional /app
    # publish
    - name: "Publish docker image (experiments image)"
      if: github.ref == 'refs/heads/master'
      run: docker push "parsertongue/realine"

